name: laravel-ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-analysis:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      APP_ENV: testing

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: laravel
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, pgsql, pdo_pgsql, curl, xml
          coverage: xdebug

      - name: Show PHP version
        run: php -v

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Wait for Postgres to be ready
        run: |
          # wait for port 5432 to be open
          for i in {1..30}; do
            if nc -z 127.0.0.1 5432; then
              echo "Postgres is up"
              break
            fi
            echo "Waiting for Postgres..."
            sleep 1
          done

      - name: Generate app key
        run: php artisan key:generate --no-interaction

      - name: Clear and cache config (after env & key are set)
        run: |
          php artisan config:clear
          php artisan config:cache

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: vendor/bin/pest --colors=always

      - name: Run code analyse
        run: vendor/bin/pint --test
