name: laravel-ci
on:
  push:
    branches:
      - main
    pull_request:

jobs:
  test-and-analysis:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: laravel
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pgsql, pdo_pgsql, curl, xml
          coverage: xdebug

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

      - name: Copy .env
        run: cp .env.example .env

      - name: Set PostreSQL variables for CI
        run: |
          php artisan config:clear
          php artisan config:cache
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=pgsql/' .env
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=5432/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=laravel/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=postgres/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=postgres/' .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --env=testing --force

      - name: Run tests
        run: vendor/bin/pest --colors=always

      - name: Run code analyse
        run: vendor/bin/pint --test
